[package]
name = "lp_tetris"
version = "0.1.0"
authors = ["Ezra Fein <bobbybobson4888@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
midir = "0.5.0"
array2d = "0.2.1"
device_query = "0.2.3"
rand = "0.6.0"