[package]
name = "lp_tetris"
version = "0.1.0"
authors = ["Ezra Barrow <bobbybobson4888@gmail.com>"]
edition = "2018"

[dependencies]
midir = "0.5.0"
array2d = "0.2.1"
multiinput = "0.0.15"
rand = "0.6.0"